# Generated by Django 2.2.4 on 2019-08-31 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("hackernewsclone", "0001_initial")]

    operations = [
        migrations.RenameField(
            model_name="post", old_name="writer", new_name="author"
        )
    ]
