# Generated by Django 2.2.4 on 2019-09-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("hackernewsclone", "0004_auto_20190906_2050")]

    operations = [
        migrations.AlterField(
            model_name="post", name="title", field=models.CharField(max_length=250)
        )
    ]
