# Generated by Django 2.2.4 on 2019-09-16 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("hackernewsclone", "0006_auto_20190909_1928")]

    operations = [
        migrations.AddField(
            model_name="post",
            name="content",
            field=models.CharField(default="", max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(name="Writer"),
    ]
